### ISSUE TITLE
Cannot dismiss any notification with 25.0.2

### ISSUE THREAD

**Issue by ranger81** [nextcloud/notifications#1425] opened 2022-12-13 15:31 UTC
A new nextcloud instance was setup using the command  
`docker run -d -p 8080:80 --name nextcloud nextcloud`

After installation, I cannot dismiss any notification. Not by pressing the "x" icon, nor using the "Dismiss all" button.
It seems to only happen with the current docker image. If I use the image with tag 24.0.8-apache, everything works fine.

**Edit: ** Problem seems to only exist with Safari browser!

**Comment by nickvergessen** [comment] 2023-01-17 21:40
Duplicate of #1418
Fixed with #1417
Coming with 25.0.4

**Closed** 2023-01-17 21:40 UTC
