### ISSUE TITLE
Notification for video visualisations are counted twice

### ISSUE THREAD

**Issue by RodSeq** [nextcloud/notifications#1848] opened 2024-03-09 19:28 UTC
Nexcloud doesn't notify the right number of visualisations of videos

### Steps to reproduce
1. Create a public link to a video stored on a NC repository
2. Open the public link of the video
3. See that the NC repository notifies 2x visualisations of the video every time that the public link is opened (or everytime that the page is refreshed) + 1x visualisation when I move the video time cursor 

### Expected behaviour
NC repository should only notifies 1x visualisation every time that the public link is opened (or refreshed)

### Actual behaviour
NC repository notifies 2x visualisations of the video every time that the public link is opened (or everytime that the page is refreshed) + 1x visualisation when I move the video time cursor 

**Operating system**:
Linux 5.4.140

**Database:**
MySQL

**PHP version:**
PHP 8.1

**Nextcloud version:** (see Nextcloud admin page)
28.0.3

**Signing status:**
Admin

**Comment by nickvergessen** [comment] 2024-03-09 19:34
Duplicate of https://github.com/nextcloud/activity/issues/1197

**Closed by nickvergessen** 2024-03-09 19:34 UTC
