### ISSUE TITLE
Consider about showing Notifications 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/notifications#2] opened 2016-07-01 14:22 UTC
I am currently not finding the discussion about that, but i think we should make the notifications-bell visible permanent  ...a bit confusing if the UI changes if you have notifications 😁 What do you think?

cc @nextcloud/designers @nickvergessen

**Comment by nickvergessen** [comment] 2016-07-01 14:32
Well I'm all for it, in the past there were decisions against it, in order to not pollute the UI. But every service I use always shows the bell.
The problem is, we don't use it for many features atm, only federated sharing (9+) and updates (10+).

**Comment by jancborchardt** [comment] 2016-07-01 14:34
I’m the one who decided we don’t show it all the time. ;) As @nickvergessen said we don’t use it for many features atm and that’s also the reason why it should not be there all the time, only when needed. As soon as it’s often used we can show it permanently.

**Comment by nickvergessen** [comment] 2016-07-01 14:42
https://github.com/owncloud/notifications/issues/65

**Comment by jancborchardt** [comment] 2016-07-01 22:07
So, I’ll close this and we can revisit it when we use Notifications for more things.

**Comment by MariusBluem** [comment] 2017-03-26 21:22
Video calls, Updates (System + Apps), ... should be enough I hope 🙏😅 ... Nextcloud 12 would be a good release to introduce it (because of the contacts menu)? @jancborchardt

**Comment by jancborchardt** [comment] 2017-03-26 21:49
What do you think @karlitschek @nickvergessen? I’d say now we could go for it, to advertise it. It might be cool to get out of stealth mode for Nextcloud 12.

**Comment by karlitschek** [comment] 2017-03-27 08:05
Not sure. What should the notification icon tell me or what should i do with it if there are no notification? I would still hide it if there are no new notifications. But maybe we could make it a bit more visible if there are notifications? for example with a bigger icon or a brighter red not?

**Comment by nickvergessen** [comment] 2017-03-27 08:31
Maybe we don't hide it on debug mode? I guess most devs use debug mode for development and then they will see it?

**Comment by jancborchardt** [comment] 2017-03-27 09:36
@karlitschek ok, fine with me. As said the icon was hidden on my request and I was under the impression you’d like to show it. ;)

@nickvergessen there should absolutely be no interface difference between what developers and users see, especially not on something as prominent as this. ;)

Closing hence. I will see to make the icon nicer.

**Comment by MariusBluem** [comment] 2017-09-03 07:48
As discussed on Conf.

**Comment by jancborchardt** [comment] 2017-09-04 09:25
@karlitschek again, what do you think:
- Rather hide the icon when there are no notifications - less distraction but also less discoverability and feedback
- Just show it always, which is quite standard from other platforms too. Then we'll have an emptycontent message in the dropdown.

**Comment by MariusBluem** [comment] 2017-12-13 13:20
Now, since Talk gets more stable I think we have more reasons showing that always ;)

**Closed** 2018-01-26 21:51 UTC
Labels: design, enhancement
