### ISSUE TITLE
Caret is misplaced

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/notifications#77] opened 2017-04-24 14:22 UTC
See:

<img width="382" alt="bildschirmfoto 2017-04-24 um 11 19 18" src="https://cloud.githubusercontent.com/assets/245432/25341733/37bab17e-28e0-11e7-9299-393dc8cb895a.png">

cc @nickvergessen

**Comment by nickvergessen** [comment] 2017-04-24 14:27
Caused by https://github.com/nextcloud/notifications/pull/70

Let's hope the contacts menu gets merged in time...
I'll leave this open as a "revert reminder" in case it's not

**Comment by nickvergessen** [comment] 2017-05-09 15:26
Contacts menu was merged, all fine again

**Closed** 2017-05-09 15:26 UTC
Labels: bug, design, papercut
