### ISSUE TITLE
Delete multiple notifications quickly makes them come back

### ISSUE THREAD

**Issue by PVince81** [nextcloud/notifications#1046] opened 2021-07-13 10:26 UTC
### Steps to reproduce

1. Have 10+ notifications, ideally spaced with a few minutes to make them easier to recognize (or different contents)
2. Have a slow instance
3. Open the bell icon dropdown
4. Quickly click on the delete icon of the top notification, then for the next one as it appears on top, etc

### Expected result
All notifications gone

### Actual
Notifications pop up again.
The network console did show a 200 OK for the DELETE operations.
If I refresh the page, the notifications are gone.

### Versions
Observed on NC 22 on c.nc.com with notifications that came from people answering to a poll from the forms app.

### Analysis

I suspect that the frontend code is not properly handling multiple deletions in parallel, and the refresh code might mistakenly reuse an old version of the collection.

**Comment by nickvergessen** [comment] 2021-07-16 13:19
Can't reproduce, I think it could be caused by the notify_push we run on c.nc.c together with our slow server.
What I think happens is the following:

1. You delete a notification
2. notify_push sends a notify to the frontend
3. notifications app triggers a fetch: 
    https://github.com/nextcloud/notifications/blob/22879575a84c732b766cdc33b3a3b7133eb9ff81/src/App.vue#L156-L158
4. The server starts response of the fetch
5. You delete another notification (and it's immediately hidden in the UI)
6. The server finishes sending the notification with the notification you deleted in 5.
7. The UI adds the notification again as it is in the list of your notifications

But seeing those steps, it could also happen when you happen to delete exactly when the 30s sync of notification happens without the notify_push.

What we could do is keep a record of successful deletes and filter them out manually on the results, but it sounds rather messy.

**Comment by nickvergessen** [comment] 2022-03-17 15:57
Should be fixed with https://github.com/nextcloud/notifications/pull/1153

**Closed by nickvergessen** 2022-03-17 15:57 UTC
Labels: bug, 1. to develop, feature: frontend 🖌️
