### ISSUE TITLE
Layout broken with mentions and actions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/notifications#387] opened 2019-07-17 10:36 UTC
Regressions from #381 and #382 cc @juliushaertl @jancborchardt 

> ![Bildschirmfoto von 2019-07-17 12-31-00](https://user-images.githubusercontent.com/213943/61368840-0dfd3b00-a88f-11e9-878c-b28f83251e0f.png)

User names are split over multiple lines

> ![Bildschirmfoto von 2019-07-17 12-31-41](https://user-images.githubusercontent.com/213943/61368842-0e95d180-a88f-11e9-98aa-63c77f08476c.png)

Action buttons don't stretch the notification body anymore and therefor overlap other notifications

**Comment by nickvergessen** [comment] 2019-07-17 10:55
Removing `display: inline-flex;` from #381 fixes the issue, so that is an option for 17, if no other solution was found.

**Comment by juliushaertl** [comment] 2019-07-17 11:42
Fix is in #388

**Closed** 2019-07-17 11:56 UTC
Labels: bug, design, feature: frontend, regression

**Comment by raimund-schluessler** [comment] 2019-08-28 11:56
Shouldn't this be fixed in NC 16.0.4 already? I still see this issue:
![Screenshot-2019-8-28 Files - Nextcloud](https://user-images.githubusercontent.com/2496460/63853684-a06b2100-c99b-11e9-915c-63bdd7311dd0.png)

**Comment by nickvergessen** [comment] 2019-08-28 12:27
I wondered the same after seeing it this week on 16.0.4
I faked the notifications on master and it looked okay there :thinking: 

@juliushaertl did we forget to backport something (I couldn't find anything missing) or do you have any other idea?

**Comment by raimund-schluessler** [comment] 2019-08-28 12:38
In stable16 the `display: inline-flex;` causing the problem is still there: https://github.com/nextcloud/notifications/blob/stable16/css/styles.scss#L132

**Comment by nickvergessen** [comment] 2019-08-28 12:42
Interesting
master: https://github.com/nextcloud/notifications/pull/388/files
automatic backport: https://github.com/nextcloud/notifications/pull/392/files

but at the same time, the code is not there in the diff around #392 

Anyway thanks for the pointed, will remove the lines

**Comment by raimund-schluessler** [comment] 2019-08-28 12:42
Looks like https://github.com/nextcloud/notifications/pull/390 / https://github.com/nextcloud/notifications/pull/392 and https://github.com/nextcloud/notifications/pull/388 somehow collided!?
