### ISSUE TITLE
Notification in Nextcloud Talk not working again ...

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/notifications#267] opened 2019-02-02 10:20 UTC
https://help.nextcloud.com/t/serveur-push-push-notifications-nextcloud-com/46648
Please reboot the server to fix it.

Can i self hosted this server on my own infrastructure?
Thx

Log:
[notifications] Error: GuzzleHttp\Exception\ServerException: Server error: `POST https://push-notifications.nextcloud.com/notifications` resulted in a `503 Service Unavailable` response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1 (truncated...)

**Comment by nickvergessen** [comment] 2019-02-02 10:41
Duplicate of #202 

Sysadmin has been notified

**Closed by nickvergessen** 2019-02-02 10:41 UTC
